### ISSUE TITLE
Automate the zip creation

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/amo2kinto-lambda#3]
Reading https://github.com/mozilla-services/amo2kinto-lambda/blob/master/docs/source/usage.rst

I think it would be easy to automate the creation of the zip by running the build on the right AMI. for example ami-f0091d91 

e.g. http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

The benefit is to make sure that the produced zip is fully compatible with amazon lambda

**Comment by Natim** [comment]
According to @tarekziade everything needed to do so can be found there: https://github.com/loads/loads-broker/blob/master/loadsbroker/aws.py
