### ISSUE TITLE
validate_signature lambda error due to stale cloudfront cache

### ISSUE THREAD

**Issue by bqbn** [mozilla-services/amo2kinto-lambda#46]
Previously, we removed the invalidate_cache lambda, and started to rely on the code in kinto-signer to do the job (i.e. invalidating the cloudfront cache).

However, today we had an issue that the validate_signature lambda failed because the cache wasn't up-to-date. As soon as we manually invalidated the cloudfront cache, the error went away.

While checking the invalidation history of the cloudfront cache, we notice that it almost always happens at 19:41 UTC (see https://screenshots.firefox.com/f4I5iwggdLa5wdmU/console.aws.amazon.com). Is there a reason why it always happens at the same time, because as far as I understand the invalidation should happen whenever people sign something, thus it makes more sense if the time were random.

The reason why 19:41 UTC might be relevant is that the alert about the lambda error happened a few minutes before 19:41, so if kinto-signer saves the task of invalidating the cache in a queue, and only does it at 19:41 every day when the queue is not empty, then it would have caused an issue like this (i.e. it waited too long to invalidate the cache). 

For reference, the lambda error we saw looks like this:
```
START RequestId: 474dc323-57ac-11e8-aef8-c361b15461c5 Version: $LATEST
Read collection list from /buckets/monitor/collections/changes
01/15 /buckets/blocklists-preview/collections/addons:  OK
02/15 /buckets/blocklists/collections/addons:  ⚠ BAD Signature ⚠
03/15 /buckets/blocklists/collections/certificates:  OK
04/15 /buckets/blocklists-preview/collections/certificates:  OK
05/15 /buckets/blocklists/collections/plugins:  OK
06/15 /buckets/blocklists-preview/collections/plugins:  OK
07/15 /buckets/security-state-preview/collections/intermediates:  SKIP
08/15 /buckets/security-state/collections/intermediates:  SKIP
09/15 /buckets/blocklists-preview/collections/gfx:  OK
10/15 /buckets/blocklists/collections/qa:  OK
11/15 /buckets/focus-preview/collections/experiments:  SKIP
12/15 /buckets/pinning-preview/collections/pins:  SKIP
13/15 /buckets/focus/collections/experiments:  SKIP
14/15 /buckets/pinning/collections/pins:  OK
15/15 /buckets/blocklists/collections/gfx:  OK

Signature verification failed on /buckets/blocklists/collections/addons
 - Signed on: 1526323825645 (2018-05-14 18:50:25 UTC)
 - Records timestamp: 1525377135149 (2018-05-03 19:52:15 UTC): ValidationError
Traceback (most recent call last):
  File "/var/task/aws_lambda.py", line 111, in validate_signature
    raise ValidationError("
" + "

".join(error_messages))
aws_lambda.ValidationError: 
Signature verification failed on /buckets/blocklists/collections/addons
 - Signed on: 1526323825645 (2018-05-14 18:50:25 UTC)
 - Records timestamp: 1525377135149 (2018-05-03 19:52:15 UTC)

END RequestId: 474dc323-57ac-11e8-aef8-c361b15461c5
REPORT RequestId: 474dc323-57ac-11e8-aef8-c361b15461c5	Duration: 70806.56 ms	Billed Duration: 70900 ms 	Memory Size: 128 MB	Max Memory Used: 83 MB	
```

**Comment by leplatrem** [comment]
On our side there is no magic:

https://github.com/Kinto/kinto-signer/blob/3ba6067962080f7227fd07ff22b8f6ff3b3de775/kinto_signer/updater.py#L364-L392

We use the boto python client to create an invalidation request in the case the distribution id setting is set.

I would say that the invalidation we see there are not coming from the python code but from somewhere else. Do we have information about the caller reference?

**Comment by bqbn** [comment]
According to CloudTrail, the API call does come from the kinto.writer instance (see https://screenshots.firefox.com/ahMUSw0wXg5TXnbI/us-west-2.console.aws.amazon.com).
