### ISSUE TITLE
Allow loading *auth keys from Env variable exposed by CloudFormation and decoded by KMS

### ISSUE THREAD

**Issue by Natim** [mozilla-services/amo2kinto-lambda#8]
A new feature in AWS Lambda is the ability to load secrets from env variables.

See https://aws.amazon.com/blogs/aws/new-for-aws-lambda-environment-variables-and-serverless-application-model/

We want to support that for json2kinto `editor_auth`, `reviewer_auth` and `auth`

**Comment by glasserc** [comment]
Is this addressed by #9?
